### ISSUE TITLE
文档doc/api.md的几个有待完善的地方

### ISSUE THREAD

**Issue by haw-haw** [ccfox-com/cloud-api#1]
- [子账户登录](https://github.com/ccfox-com/cloud-api/blob/master/doc/api.md#子账号登录)的“返回数据”中的字段“scope”返回的是什么信息？
<img width="970" alt="WechatIMG289" src="https://user-images.githubusercontent.com/506263/82807896-47dd9b80-9ebb-11ea-8992-330eea434c10.png">

- [子账户注册](https://github.com/ccfox-com/cloud-api/blob/master/doc/api.md#子账号注册)中最后“返回数据”中的字段“data”是返回的什么信息？是登录信息吗？
<img width="1099" alt="WechatIMG292" src="https://user-images.githubusercontent.com/506263/82807907-4dd37c80-9ebb-11ea-9795-a64ea421af39.png">

- [子账户登录](https://github.com/ccfox-com/cloud-api/blob/master/doc/api.md#子账号登录)的“返回数据”中的字段：access_token、token_type 和 refresh_token 的具体描述
<img width="966" alt="WechatIMG281" src="https://user-images.githubusercontent.com/506263/82807886-41e7ba80-9ebb-11ea-9545-d3bdc87b98d8.png">

**Comment by qzsheng** [comment]
合约云对接，只关注: access_token(访问令牌)
